### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by NayeliMoraless** [SistemasTecTlaxiaco/infografia-de-hilos-NayeliMoraless#2]
[info hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-NayeliMoraless/files/15113430/info.hilos.pdf)

**Comment by Aylin67** [comment]
18%
FALTO CREDITOS.

**Comment by josealfredo79** [comment]
bien hecho y revisado..
